name: PennyPilot CI/CD Deploy to EC2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: algorithm_alliance
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: pennypilot_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U algorithm_alliance"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Backend Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Backend Tests (if present)
      env:
          SQLALCHEMY_DATABASE_URI: ${{ secrets.SQLALCHEMY_DATABASE_URI }}
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
          PLAID_ENV: ${{ secrets.PLAID_ENV }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        if [ -d "backend/tests" ]; then
          pytest backend/tests
        else
          echo "No backend tests found — skipping"
        fi
      
  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install Frontend Dependencies
      run: npm ci
      working-directory: .
    - name: Build Frontend
      env:
        VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
        VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
        VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
        VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
      run: npm run build
      working-directory: .

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/pennypilot
            git pull origin main

            # Overwrite .env if ENV_FILE is provided
            if [ ! -z "${{ secrets.ENV_FILE }}" ]; then
              echo "${{ secrets.ENV_FILE }}" > .env
            fi

            cd ~/pennypilot
            npm install
            NODE_OPTIONS="--max-old-space-size=2048" npm run build

            sudo systemctl restart pennypilot
          EOF
    